### ISSUE TITLE
Issue with tooltip of Button when hasIconOnly is true

### ISSUE THREAD

**Issue by printfhere** [IBM/carbon-components-svelte#387]
Hi, I have a problem when creating a Button with hasIconOnly. 
1. After the click the tooltip does not disappear until I click somewhere else.
2. My button is near the border of my page and I can't see it properly
3. I would need a way to disable the tooltip of these icon buttons

Some tips?

**Comment by metonym** [comment]
By design, the icon-only Button must display a tooltip when hovering/focusing the button.

1. This is expected. The button should remain focused until the focus is stolen by another element.
2. Use the `tooltipPosition` and `tooltipAlignment` props to adjust the tooltip position
3. If hiding the tooltip is a hard requirement, you can always use CSS to visually hide the tooltip.

**Comment by printfhere** [comment]
Hi thanks for your answer, I will definetely try to hide it with some css.

**Comment by metonym** [comment]
Refer to this discussion to hide a tooltip using CSS: https://github.com/carbon-design-system/carbon-components-svelte/discussions/1483
