### ISSUE TITLE
Inconsistent use of rest props with DataTable and DataTableSkeleton

### ISSUE THREAD

**Issue by ispyinternet** [IBM/carbon-components-svelte#423]
For me this appeared because I wanted to control the class on the DataTable container to add x-scroll. I would like that to be consistent across the DataTable and the DataTableSkeleton, however in the skeleton, you pass the rest props directly to the table bypassing the data table container (`bx--data-table-container`), whereas in the DataTable you apply rest props to the container.

I would submit a fix, but I'm unsure how you want to address this?

**Comment by metonym** [comment]
I agree – spreading rest props to the same class name "bx--data-table-container" makes sense.

I think that spreading rest props in `DataTableSkeleton` to the top-level "bx--data-table-container" element instead of the `table` element would be the best approach. If I recall correctly, the initial top-level element in `DataTableSkeleton` was the table element. The container div was added later.

**Comment by ispyinternet** [comment]
I've actioned that, do I need to do anything to keep the git commits / history clean?

https://github.com/IBM/carbon-components-svelte/compare/master...ispyinternet:master

**Comment by metonym** [comment]
Feel free to submit a PR.

**Comment by metonym** [comment]
This was released in v0.26.0
