### ISSUE TITLE
Sapper: Export Size is huge

### ISSUE THREAD

**Issue by gurugeek** [IBM/carbon-components-svelte#471]
I downloaded the example and the first issue 

`import "carbon-components-svelte/css/all.css";`

I changed this to` import "carbon-components-svelte/css/g10.css";` but no matter what the export is still huge. Nota bene that both g10.css and all.css are not even minified. I removed the fonts in unused languages and minified it but no matter what, the result is a 400K css file.  I did see #https://github.com/IBM/carbon-components-svelte/issues/137 but I am not sure if this is totally applicable to sapper users. (As per example this is imported in the client and not as a style).

If it does can someone update the example with the best way to use carbon in sapper ?

**Comment by metonym** [comment]
If you're looking to optimize the CSS output, have a look at this [guide on using Carbon SCSS](https://github.com/carbon-design-system/carbon/blob/master/docs/guides/sass.md#optimizing-your-sass-builds).

If using sass, you'll also need the following dependencies:

- carbon-components
- sass
- svelte-preprocess
- autoprefixer

**Comment by gurugeek** [comment]
@metonym thanks for your reply.  Much appreciated!

This said, I am a bit confused: what is the point to have a package carbon-component-svelte that can be used in sapper (as per readme and example) that generates a huge css (a simple blog with few pages get a 40% score on google page speed insight even with `import "carbon-components-svelte/css/g10.css";` and having all the fonts removed (I use google fonts with pre-load on the template) and then recommend to use carbon components, sass, svelte pre-process and autoprefixer ?
The guide also seems to be for something else (react?).

I think the sapper example should be improved. Perhaps the ` carbon-components-svelte/css/` should be minified (this won't make much difference thou).  I can certainly optimise the CSS by removing what I don't need but I just wanted to check i this is the best option without having to install 4 extra dependencies and essentially moving out of carbon-component-svelte  + sapper example.

**Comment by metonym** [comment]
@gurugeek 

I see your point. If you're using only a few components, it's overkill to include all CSS. It's worth exploring use cases where all you need is the Grid, Link, typography/layout styles etc. like for a blog.

> The guide also seems to be for something else (react?)

The guide is from the flagship Carbon repository, which serves as official guidance from the Carbon team. The guide on SCSS is framework/language agnostic and not specific to React.

> without having to install 4 extra dependencies

**That's the cost of optimizing the CSS output by using SCSS.**

To incorporate SCSS you need those extra dependencies in your dev workflow to be able to import individual component styles. And actually, I think it's more than 4 dependencies because PostCSS is also required (since version 10).

This is one reason for pre-compiling CSS per theme: convenience.

**Comment by gurugeek** [comment]
I understand, thank you for the reply.
