### ISSUE TITLE
3 button modal has room for 4 buttons

### ISSUE THREAD

**Issue by weaseldotro** [IBM/carbon-components-svelte#728]
https://carbon-svelte.vercel.app/framed/Modal/3ButtonModal
There is room for 4 buttons but only 3 are displayed, there is a blank space whew the first button would be.

**Comment by metonym** [comment]
I believe the design is intentional.

This is a screenshot of the [3 button modal in Carbon React](https://react.carbondesignsystem.com/?path=/story/components-modal--playground):

![modal-three-button](https://user-images.githubusercontent.com/10718366/124517551-19f2a800-dd99-11eb-8085-a4c099a2e6e8.png)

A similar motif appears on the [Carbon component guidance for modals](https://carbondesignsystem.com/components/modal/usage/):

![modal-carbon](https://user-images.githubusercontent.com/10718366/124517631-4a3a4680-dd99-11eb-95a0-673f98fe25ba.png)

**Comment by weaseldotro** [comment]
Yep, you're right, this is an upstream issue and not really within the scope of this library. I guess I should have checked there first, sorry for wasting your time.

But damn it looks so bad, especially on phones where the first button container is a lot smaller than the others. I'll open an issue on the main carbon repo.
